Trigger travis

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -31,14 +31,14 @@ install:
   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PATH=/usr/local/bin:${PATH}; fi
   
   # Install a recent CMake (unless already installed on OS X)
-  - |
-  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
-    CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz"
-    mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
-    export PATH=${DEPS_DIR}/cmake/bin:$PATH
-  else 
-    if ! brew ls --version cmake &>/dev/null; then brew install cmake; fi
-  fi
+#  - |
+#  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
+#    CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz"
+#    mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
+#    export PATH=${DEPS_DIR}/cmake/bin:$PATH
+#  else 
+#    if ! brew ls --version cmake &>/dev/null; then brew install cmake; fi
+#  fi
   
 # APT (Linux)
 addons:
